# Generated by Django 3.0.6 on 2020-05-17 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 14, 46, 5, 297440, tzinfo=utc), verbose_name='date published'),
        ),
    ]
